name: deploy labs auto
on:
  workflow_run:
    workflows: [build]
    types: [completed]

env:
  IMAGE: ghcr.io/${{ github.repository }}/fake-produsent-api:${{ github.event.workflow_run.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          DEPLOY_SERVER: deploy.nais.io:443
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: nais-application.yaml
