name: deploy labs manual
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        name: "deploy labs ${{ github.ref }}"
        env:
          IMAGE: ghcr.io/${{ github.repository }}/fake-produsent-api:${{ github.sha }}
          REF: ${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: nais-application.yaml

