name: deploy dev auto
on:
  workflow_run:
    workflows: [build]
    types: [completed]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: config/nais-application.yaml
